name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-python@v1
    - name: Install conan && conan package tools
      run: |
        python -m pip install --upgrade pip
        pip install conan
        pip install conan_package_tools
    - uses: actions/checkout@v1
    - name: conan
      run: |
        conan install . -s compiler.libcxx=libstdc++11
    - name: cmake
      run: |
        find /home/runner/.conan -name '*.so*'
        cmake . -DCMAKE_TOOLCHAIN_FILE=conan_paths.cmake
        cmake --build .
        ctest --output-on-failure
        
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with: 
        # Artifact name
        name: action
        # Directory containing files to upload
        path: ./src
         
