name: Conan

on: [push]

jobs:
  conan:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            python-arch: "x64"
            python-version: "3.6.x"
            gcc-version: "7"
            install-headerfiles: true

    runs-on: ${{ matrix.os }}

    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        version: ${{ matrix.python-version }}
        architecture: ${{ matrix.python-arch }}
    - name: Install conan && conan package tools
      run: |
        python -m pip install --upgrade pip
        pip install conan
        pip install conan_package_tools
    - name: Install C and C++ header files
      run: |
        sudo apt-get update && sudo apt-get install -y gcc-multilib
      if: matrix.install-headerfiles
    - uses: actions/checkout@v1
    - name: Generating conan user directory and building the solution
      run: |
        conan user
        cd conan && python build.py
      env:
        CONAN_REFERENCE: "actions/0.1"
        CONAN_USERNAME: "canmor"
        CONAN_LOGIN_USERNAME: "canmor"
        CONAN_CHANNEL: "testing"
        CONAN_UPLOAD: "https://api.bintray.com/conan/conan/actions"
        CONAN_STABLE_BRANCH_PATTERN: "release/*"
        CONAN_GCC_VERSIONS: ${{ matrix.gcc-version }}
        #CONAN_APPLE_CLANG_VERSIONS: "11.0"
        #CONAN_VISUAL_VERSIONS: ${{ matrix.vs-version }}
